name: Main checks
on: [push, pull_request]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Set up yarn
        run: yarn

      - name: Run yarn audit
        run: yarn improved-yarn-audit

      - name: Run tsc
        run: yarn tsc --noEmit

      - name: Run lint
        run: yarn lint

      - name: Run prettier
        run: yarn prettier:check
